import io
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import HRFlowable


def generate_trip_pdf(itinerary_text, source, destination, num_days, travel_date, budget):
    """
    Generate a PDF itinerary and return it as a bytes buffer.

    Args:
        itinerary_text (str): The full itinerary text from the AI agent.
        source (str): Departure city.
        destination (str): Destination city.
        num_days (int): Number of trip days.
        travel_date (str): Travel start date.
        budget (int/float): Trip budget in INR.

    Returns:
        bytes: PDF content as bytes (suitable for st.download_button).
    """
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()

    # ── Custom styles ──────────────────────────────────────────
    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        fontSize=24,
        textColor=colors.HexColor("#302b63"),
        spaceAfter=6,
        fontName="Helvetica-Bold",
    )

    subtitle_style = ParagraphStyle(
        "SubtitleStyle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#f5576c"),
        spaceAfter=4,
        fontName="Helvetica-Bold",
    )

    detail_style = ParagraphStyle(
        "DetailStyle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#333333"),
        spaceAfter=3,
        leading=16,
    )

    body_style = ParagraphStyle(
        "BodyStyle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#222222"),
        spaceAfter=6,
        leading=16,
        wordWrap="LTR",
    )

    footer_style = ParagraphStyle(
        "FooterStyle",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.HexColor("#888888"),
        alignment=1,  # center
        fontName="Helvetica-Oblique",
    )

    # ── Build story (content elements) ────────────────────────
    story = []

    # Title
    story.append(Paragraph("✈ AI Travel Itinerary", title_style))
    story.append(Spacer(1, 0.3 * cm))

    # Divider
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#f093fb")))
    story.append(Spacer(1, 0.4 * cm))

    # Trip details block
    story.append(Paragraph("Trip Summary", subtitle_style))
    story.append(Paragraph(f"<b>From:</b> {source}", detail_style))
    story.append(Paragraph(f"<b>To:</b> {destination}", detail_style))
    story.append(Paragraph(f"<b>Duration:</b> {num_days} day{'s' if num_days != 1 else ''}", detail_style))
    story.append(Paragraph(f"<b>Travel Date:</b> {travel_date}", detail_style))
    story.append(Paragraph(f"<b>Budget:</b> ₹{int(budget):,}", detail_style))
    story.append(Spacer(1, 0.3 * cm))

    # Divider
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cccccc")))
    story.append(Spacer(1, 0.4 * cm))

    # Itinerary heading
    story.append(Paragraph("Full Itinerary", subtitle_style))
    story.append(Spacer(1, 0.2 * cm))

    # Itinerary body — split into paragraphs on blank lines
    for para in itinerary_text.split("\n"):
        clean = para.strip()
        if clean:
            # Escape any HTML-like characters so reportlab doesn't choke
            clean = (
                clean
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
            )
            story.append(Paragraph(clean, body_style))
        else:
            story.append(Spacer(1, 0.2 * cm))

    story.append(Spacer(1, 0.6 * cm))

    # Divider
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cccccc")))
    story.append(Spacer(1, 0.3 * cm))

    # Footer
    story.append(Paragraph("Generated by AI Travel Planner 🤖 — Always verify prices and availability before booking.", footer_style))

    # ── Build PDF ──────────────────────────────────────────────
    doc.build(story)

    buffer.seek(0)
    return buffer.read()